---
# Version: 1.2.0
# Description: Prepare Moodle schema for Solr core
# Moodle Compatibility: 4.1, 4.2, 4.3, 4.4, 5.0.x


- name: moodle-schema - Generate Moodle schema XML
  template:
    src: moodle_schema.xml.j2
    dest: "{{ solr_config_dir }}/moodle_schema.xml"
    owner: root
    group: root
    mode: '0644'
  become: true
  when: solr_use_moodle_schema | default(true)

- name: moodle-schema - Verify Moodle schema file exists
  stat:
    path: "{{ solr_config_dir }}/moodle_schema.xml"
  register: moodle_schema_check
  when: solr_use_moodle_schema | default(true)

- name: moodle-schema - Display schema preparation status
  debug:
    msg:
      - "MOODLE SCHEMA PREPARATION"
      - "Schema file: {{ solr_config_dir }}/moodle_schema.xml"
      - "Schema exists: {{ moodle_schema_check.stat.exists }}"
      - "Moodle compatibility: 4.1, 4.2, 4.3, 4.4, 5.0.x"
      - "Fields: id, title, content, contextid, courseid, owneruserid, etc."
  when: solr_use_moodle_schema | default(true)

- name: moodle-schema - Create Rundeck-compatible output
  set_fact:
    moodle_schema_result:
      status: "success"
      timestamp: "{{ ansible_date_time.iso8601 }}"
      message: "Moodle schema preparation completed"
      details:
        schema_file: "{{ solr_config_dir }}/moodle_schema.xml"
        schema_exists: "{{ moodle_schema_check.stat.exists if moodle_schema_check is defined else false }}"
        moodle_versions: ["4.1", "4.2", "4.3", "4.4", "5.0.x"]
        required_fields:
          - "id (unique identifier)"
          - "title (document title)"
          - "content (searchable text)"
          - "contextid (Moodle context)"
          - "courseid (course ID)"
          - "owneruserid (owner user ID)"
          - "modified (timestamp)"
          - "type (document type)"
          - "areaid (search area)"
          - "itemid (item ID)"

- name: moodle-schema - Display Rundeck output
  debug:
    msg: "{{ moodle_schema_result | to_nice_json }}"
  when: rundeck_integration_enabled | default(false)